            - name: chatgpt-action
  # You may pin to the exact commit or the version.
  # uses: unsafecoerce/chatgpt-action@df5b73b6f2d8b7f16a51de0f2f3810bd320b053e
  uses: unsafecoerce/chatgpt-action@release/v2
  with:
    # The action to run, currently can be "review", "score"
    action: # optional, default is review
    # Enable debug mode
    debug: # optional
    # The path filters, e.g., "src/**.py", "!dist/**", each line will be considered as one pattern.
See also

- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
- https://github.com/isaacs/minimatch

    path_filters: # optional, default is !dist/**
!**/package-lock.json

    # The URL of the chatgpt reverse proxy, see also https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy

    chatgpt_reverse_proxy: # optional, default is https://chat.duti.tech/api/conversation
    # Leave comments even the patch is LGTM
    review_comment_lgtm: # optional
    # The beginning prompt of a code review dialog
    review_beginning: # optional, default is Hi ChatGPT, I have a pull request with title "$title" and the description is as follows,

> $description.

Next, I will given you a series of patches, each of them consists of a filename and a diff
snippet, and you need to do a brief code review for every message, and tell me any bug risk
and improvement suggestion. If the patch is looks good and acceptable, please reply "LGTM!"
with a short comment with 30 words.

You answer should be concise. Don't include the diff in your comment, and markdown format is
preferred. Reply "OK" to confirm.

    # The prompt for each chunks/patches
    review_patch: # optional, default is $filename

```diff
$patch
```

    # The prompt for the whole pull request
    scoring_beginning: # optional, default is Hi ChatGPT, I have a pull request with title "$title" and the description is as follows,

> $description

I would like score the pull request, the score should be a number between 0 and 100
and 85 means the the pull request is basically acceptable. You just need to reply a
number between 0 and 100, e.g., "85", and a comment within 30 words. Next, I would
give you the whole diff of the pull request. Reply "OK" to confirm.

    # The prompt for the whole diff for scoring
    scoring: # optional, default is The diff is as follows:

```diff
$diff
```

          
